In [3]:
import numpy as np

# 修改数组元素

In [22]:
t=np.arange(30).reshape(5,6)
t[(t>5)&(t<20)]=10 # 与
t[(t<6)|(t>25)]=-1 # 或
t[~(t<=19)]=5 # 非
print(t)

[[-1 -1 -1 -1 -1 -1]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10  5  5  5  5]
 [ 5  5 -1 -1 -1 -1]]


In [23]:
t=np.where(t==10,True,False)
print(t)

[[False False False False False False]
 [ True  True  True  True  True  True]
 [ True  True  True  True  True  True]
 [ True  True False False False False]
 [False False False False False False]]


In [29]:
# 往哪个轴添加，哪个轴的size就变大
a=np.array([[1,2,3],[4,5,6]])
print('不指定轴，则展开：')
print(np.append(a, [7,8,9]))
print('沿轴0添加元素：')
print(np.append(a, [[7,8,9]],axis=0))
print('沿轴1添加元素：')
print(np.append(a, [[5,5,5], [7,8,9]],axis=1))

不指定轴，则展开：
[1 2 3 4 5 6 7 8 9]
沿轴0添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]
沿轴1添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
